# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='avatars/')),
            ],
            options={
                'permissions': (('can_create_provider', 'Can create provider'), ('can_delete_provider', 'Can delete provider'), ('can_update_provider', 'Can update provider')),
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
            },
        ),
    ]
