# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Provider',
            new_name='Brand',
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'permissions': (('can_create_brand', 'Can create brand'), ('can_delete_brand', 'Can delete brand'), ('can_update_brand', 'Can update brand')), 'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
    ]
