# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 14:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('bio', models.TextField(blank=True, max_length=200)),
                ('genre', models.IntegerField(choices=[(1, 'Hombre'), (2, 'Mujer')], default=1)),
                ('avatar', models.ImageField(blank=True, upload_to='user/profile/avatar')),
                ('birthday', models.DateField(blank=True)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'permissions': (('can_create_employee', 'Can create employee'), ('can_delete_employee', 'Can delete employee'), ('can_update_employee', 'Can update employee')),
            },
        ),
        migrations.CreateModel(
            name='ProfileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'permissions': (('can_create_profile', 'Can create profile'), ('can_delete_profile', 'Can delete profile'), ('can_update_profile', 'Can update profile'), ('is_office_user', 'Is an user from the office'), ('is_office_provider', 'Is an office provider'), ('is_store_user', 'Is an user from an store'), ('is_store_provider', 'Is an provider')),
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='profiletype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.ProfileType'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
